#! /bin/bash

# Globals
EXTENSIONS_FILE="extensions.txt"

# Functions
log_error()
{
	printf "\e[31mERROR:\e[0m $1\n"
}

help()
{
	cat << EOF
Synchronize extensions with "$EXTENSIONS_FILE".

help			show this help
update			save current extensions to "$EXTENSIONS_FILE"
install			install all extensions in "$EXTENSIONS_FILE"
EOF
}

update()
{
	code --list-extensions > "$EXTENSIONS_FILE"
}

install()
{
	while read ext; do
		code --install-extension "$ext"
	done < "$EXTENSIONS_FILE"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
	key="$1"

	case $key in
		help)
			help
			exit 0
	 	;;
		update)
			update
			exit 0
		;;
		install)
			install
			exit 0
		;;
		*)
			log_error "unknown option $key"
			help
			exit 1
		;;
	esac
done
